Web graphics sep
NOAA-GSD/adb_graphics pull request #54
Opened 2020-09-15 01:50 UTC by cshartsough

Adds 5-6 new snow/freezing precip fields. Adds a fix for thickness overlay.  New conversion test.

pylint and pytest completed.

Will add figures next.

2020-09-15 01:51 UTC, cshartsough commented
[web-graphics_PR-54.pptx](https://github.com/NOAA-GSD/adb_graphics/files/5222005/web-graphics_PR-54.pptx)

2020-09-15 14:01 UTC, christinaholtNOAA requested changes
The graphics look good. I like that you changed 1hr acc snow colors to be consistent with the other products. :)

A bit worried (currently) about the thickness fix. Let me check that out and get back to you.

2020-09-15 14:30 UTC, cshartsough commented on adb_graphics/default_specs.yml
> +    clevs: !!python/object/apply:numpy.arange [550, 600, 5]
It's no problem to set the interval to 6, I was just debugging last night with different clevs.

I don't know what the original clevs range is for, unless we only expect to use the field as overlays and don't care how big a set of levels it generates.  I can put it back to the original values.

2020-09-15 14:50 UTC, christinaholtNOAA commented on adb_graphics/default_specs.yml
> +    clevs: !!python/object/apply:numpy.arange [550, 600, 5]
Okay! I found the bug I introduced that causes this problem. In datahandler/grib.py, near line 158, it should read:

```lev_val, _ = self.numeric_level(level=level)```

You want to pop that in and remove all the changes to the default_specs.yml for these two gh sections to see what happens?

2020-09-15 15:12 UTC, cshartsough commented on adb_graphics/default_specs.yml
> +    clevs: !!python/object/apply:numpy.arange [550, 600, 5]
Yes, that seems to work.  Thanks.

2020-09-15 17:11 UTC, cshartsough commented on adb_graphics/default_specs.yml
> +    clevs: [0.01, 0.1, 1, 2, 3, 4, 6, 8, 10, 12, 18, 24]
I anchored acfrzr and acfrozr.  I didn't anchor acpcp, but did merge color tables for accumulated_precip_hourly, rh_colors, and hlcy_colors, into rainbow12_colors.

2020-09-17 14:08 UTC, christinaholtNOAA approved these changes
Looks great! Thanks for the changes.

2020-09-17 14:43 UTC, Brian-Jamison approved these changes
All looks good!  Thanks!

2020-09-17 16:22 UTC, merged