Windspeed
NOAA-GSD/adb_graphics pull request #57
Opened 2020-09-22 20:06 UTC by Brian-Jamison

These are the specifications for windspeed plots (10m wind, max 10m wind, 80m wind, 850mb wind, 250mb wind, max updraft, and max downdraft).

Examples with their NCL counterparts follow:

![wind_10m_f06](https://user-images.githubusercontent.com/58485074/93931439-04b1fe80-fcdc-11ea-9323-c8925480d4ea.png)
![wspeed10m_f006](https://user-images.githubusercontent.com/58485074/93931570-34610680-fcdc-11ea-9d85-a68468296a6d.png)
![wind_max_f06](https://user-images.githubusercontent.com/58485074/93931646-52c70200-fcdc-11ea-8094-76f5a4a2c9e7.png)
![wspeedmax_f006](https://user-images.githubusercontent.com/58485074/93931681-5b1f3d00-fcdc-11ea-809e-a63d1a8f40bc.png)
![wind_80m_f06](https://user-images.githubusercontent.com/58485074/93931709-64100e80-fcdc-11ea-8209-3d8ef5dcd9bd.png)
![wspeed80m_f006](https://user-images.githubusercontent.com/58485074/93931739-6c684980-fcdc-11ea-9e99-bc63d42c5338.png)
![wind_850_f06](https://user-images.githubusercontent.com/58485074/93931794-8013b000-fcdc-11ea-92c8-96cdde5c55df.png)
![wspeed850mb_f006](https://user-images.githubusercontent.com/58485074/93931828-8a35ae80-fcdc-11ea-8ef2-e25aaaefc7a1.png)
![wind_250_f06](https://user-images.githubusercontent.com/58485074/93931855-928de980-fcdc-11ea-87da-f7b68201485f.png)
![wspeed250mb_f006](https://user-images.githubusercontent.com/58485074/93931879-9ae62480-fcdc-11ea-84ab-fab5a59393f1.png)
![wind_mdn_f06](https://user-images.githubusercontent.com/58485074/93931910-a46f8c80-fcdc-11ea-8798-aa449870601c.png)
![wspeedmdn_f006](https://user-images.githubusercontent.com/58485074/93931937-acc7c780-fcdc-11ea-96e1-3a14373cf1c9.png)
![wind_mup_f06](https://user-images.githubusercontent.com/58485074/93931960-b6512f80-fcdc-11ea-9582-48fed2bee30a.png)
![wspeedmup_f006](https://user-images.githubusercontent.com/58485074/93931985-be10d400-fcdc-11ea-9ed1-464b157597da.png)

2020-09-22 20:11 UTC, Brian-Jamison commented
Sorry, wrong images for 250mb and 850mb.
![wind_850_f06](https://user-images.githubusercontent.com/58485074/93932461-7b033080-fcdd-11ea-865b-cfe8e4b5994a.png)
![wind_250_f06](https://user-images.githubusercontent.com/58485074/93932471-7e96b780-fcdd-11ea-9f1e-add7d69aae87.png)

2020-09-22 20:32 UTC, christinaholtNOAA requested changes
I made a couple of in-line comments on some minor things that should still be addressed below.

Also, you brought up an issue with plotting the correct vector magnitude values in Slack. How was that addressed to get the nice looking plots you attached here?

2020-09-22 20:32 UTC, christinaholtNOAA commented on adb_graphics/specs.py
> +    def mup_colors(self) -> np.ndarray:
Please rearrange the whitespace here to match the others. This should also be moved down to be in order with the next method.

2020-09-22 20:32 UTC, christinaholtNOAA commented on adb_graphics/specs.py
> +        others = cm.get_cmap('jet', 18)(range(18, 1, -1), alpha=0.6)
The names of the colormaps should be set in default_specs.yml instead of hard coding here. This also applies to the other color definitions below.

2020-09-22 21:29 UTC, Brian-Jamison commented
Thanks, @christinaholtNOAA, I've fixed the whitespace and cmap issues.

I had realized that the magnitude field is given in the grib2 file explicitly.  It doesn't need to be computed via the components.  The component fields are, however, used in plotting the wind barbs.

2020-09-23 01:47 UTC, cshartsough approved these changes
good job, a lot of work here.

Thanks for the thorough review, Christina.

2020-09-23 20:18 UTC, christinaholtNOAA approved these changes
Looks good!

2020-10-13 18:24 UTC, cshartsough commented
just doing another quick review on GitHub.   Do the u and v max wind fields need an anchor like the other levels?
max:
     ncl_name: MAXUW_P8_L103_{grid}_max1h
     transform: conversions.ms_to_kt
otherwise it looks good.

2020-10-13 18:26 UTC, Brian-Jamison commented
No, no anchors necessary, since the magnitude field is available from the grib2 file, we don't have to compute it.

2020-10-13 18:33 UTC, christinaholtNOAA commented
Looks good to me!

2020-10-13 18:57 UTC, merged